spring:
  application:
    name: study-reserve-system
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  datasource:
    username: root
    password: 12345
    url: jdbc:mysql://localhost:3306/study_reserve_db?useSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  servlet:
    session:

      timeout: 5m